# Site settings
title: h log
email: hoj201@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A place to view my rants. Testing testing... 123.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hoj201.github.io" # the base hostname & protocol for your site
github_username:  hoj201

# Build settings
markdown: kramdown
