# Site settings
title: Milk Bar
email: "hoj201@gmail.com"
me: 
  name: Henry O. Jacobs
  email: hoj201@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my draft blog.  My actual blog is at [the new flesh](https://www.thenewflesh.net/)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hoj201.github.io" # the base hostname & protocol for your site
github_username: hoj201
theme: minima
# Build settings
markdown: kramdown
disqus:
  shortname: hoj201-github-io
google_analytics: UA-104975181-2
