# Site settings
title: Milk Bar
email: hoj201@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welly welly welly well. Take a viddy at me posts.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hoj201.github.io" # the base hostname & protocol for your site
github_username: hoj201
theme: minima
# Build settings
markdown: kramdown
disqus:
  shortname: hoj201-github-io
